spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/microservices
      database: microservices

  application:
    name: RATING-SERVICE

server:
  port: 8083

  discovery:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka